### ISSUE TITLE
Feature Request: Non flowing Liquid Blocks

### ISSUE THREAD

**Issue by Darkosto** [HenryLoenwind/extrabedrock#1]
Hey Henry!

Would you be willing to add a non-flowing version of the liquid blocks? I would like to have my ocean worlds use the water or lava variants but not be flowing into the void.

Thank you!

**Comment by HenryLoenwind** [comment]
Hi,

when you place them at y=0 they won't flow down into the void. Their flowing mechanics is to place source blocks under them (and to their sides), which obviously isn't possible at y=0. (Neither flowing water nor flowing lava accepts a modded block as "source", that's why my blocks place source blocks.) Having them at y=0 without downflowing was one of my design goals.

Is this enough for you?

**Comment by Darkosto** [comment]
Hey! This should work, we were testing a little higher than y=1 and did not see the flow stop at 0. Thanks for the response :)
